# Generated by Django 3.2.9 on 2022-04-22 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DarkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observing_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('letter', models.CharField(max_length=1)),
                ('position', models.PositiveSmallIntegerField()),
                ('flat_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FilterWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('ip', models.GenericIPAddressField()),
                ('device_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter_wheel.filter')),
            ],
        ),
        migrations.CreateModel(
            name='MasterFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('flats', models.ManyToManyField(to='filter_wheel.FlatImage')),
            ],
        ),
        migrations.CreateModel(
            name='MasterDark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observing_time', models.FloatField()),
                ('darks', models.ManyToManyField(to='filter_wheel.DarkImage')),
            ],
        ),
        migrations.AddField(
            model_name='flatimage',
            name='master_dark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter_wheel.masterdark'),
        ),
        migrations.AddField(
            model_name='filter',
            name='filter_wheel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter_wheel.filterwheel'),
        ),
    ]
