# Generated by Django 4.1.6 on 2023-07-03 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_camera_port_alter_camera_device_id_alter_camera_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.PositiveIntegerField(default=0)),
                ('start_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=4096)),
                ('height', models.PositiveIntegerField(default=4096)),
                ('bin_x', models.PositiveSmallIntegerField(default=1)),
                ('bin_y', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReadOutTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.frame')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure_time', models.FloatField(default=1, help_text='Exposure time in seconds')),
                ('dark', models.BooleanField(blank=True, default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camera.frame')),
            ],
        ),
    ]
