# Generated by Django 4.1.6 on 2023-07-07 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filter_wheel', '0002_filterwheel_port_alter_filterwheel_device_id_and_more'),
        ('camera', '0004_image_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='fits_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='ImageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure_time', models.FloatField(default=1, help_text='Exposure time in seconds')),
                ('dark', models.BooleanField(blank=True, default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('repeats', models.PositiveSmallIntegerField(default=1)),
                ('images_done', models.PositiveSmallIntegerField(default=0)),
                ('filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter_wheel.filter')),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camera.frame')),
                ('observer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
