# Generated by Django 3.2.9 on 2022-04-22 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filter_wheel', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observing_start', models.DateTimeField()),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.catalogitem')),
                ('master_dark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter_wheel.masterdark')),
                ('master_flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter_wheel.masterflat')),
            ],
        ),
    ]
