# Generated by Django 4.1.6 on 2023-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind', models.FloatField(help_text='The wind velocity in m/s')),
                ('wind_2m', models.FloatField(help_text='The wind velocity in m/s 2 meters above the ground')),
                ('temperature', models.FloatField(help_text='The outside temperature')),
                ('temperature_dome', models.FloatField(help_text='The temperature inside the dome')),
                ('dewpoint', models.FloatField(help_text='Dewpoint ')),
                ('humidity', models.FloatField(help_text='The outside humidity')),
                ('humidity_dome', models.FloatField(help_text='The humidity inside the dome')),
                ('rain', models.FloatField(help_text='Rain')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The current time')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL of the weather page')),
                ('date', models.DateTimeField(auto_now=True, help_text='The time of the latest change')),
            ],
        ),
    ]
