# Generated by Django 4.1.6 on 2023-06-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogitem',
            old_name='observation_time',
            new_name='exposure_time',
        ),
        migrations.AddField(
            model_name='target',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='target',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
