# Generated by Django 4.1.6 on 2023-07-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter_wheel', '0001_initial'),
        ('catalog', '0002_rename_observation_time_catalogitem_exposure_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the type like "Exoplanet", "QSO" and so on', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='capture',
            field=models.ImageField(blank=True, help_text='Preview of the target', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='The datetime when the entry was created'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='exposure_time',
            field=models.FloatField(help_text='The exposure time in seconds'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='filter',
            field=models.ForeignKey(help_text='The to used filter', null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter_wheel.filter'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='name',
            field=models.CharField(help_text='Name of the catalog entry', max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='target',
            field=models.ForeignKey(help_text='The target for this catalog entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.target'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The datetime when the entry was updated the last time'),
        ),
        migrations.AlterField(
            model_name='target',
            name='dec',
            field=models.FloatField(help_text='Dec in degrees'),
        ),
        migrations.AlterField(
            model_name='target',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Additional description of the target'),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Name of the target', max_length=100),
        ),
        migrations.AlterField(
            model_name='target',
            name='ra',
            field=models.FloatField(help_text='RA in hour float'),
        ),
        migrations.AddField(
            model_name='target',
            name='type',
            field=models.ForeignKey(help_text='The type of the target', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.type'),
        ),
    ]
