# Generated by Django 4.1.6 on 2023-07-11 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_temperature'),
        ('catalog', '0003_type_alter_catalogitem_capture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='frame',
            field=models.ForeignKey(help_text='The used camera frame', null=True, on_delete=django.db.models.deletion.SET_NULL, to='camera.frame'),
        ),
    ]
