# Generated by Django 4.1.6 on 2023-07-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_catalogitem_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField(help_text='Latitude of the location in degrees')),
                ('longitude', models.FloatField(help_text='Longitude of the location in degrees')),
                ('altitude', models.FloatField(help_text='Altitude of the location in meters')),
            ],
        ),
    ]
