# Generated by Django 4.1.6 on 2023-07-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('azimuth_limit', models.FloatField(help_text='Maximal limit after which the dome is moved actively to be aligned with the mount in degrees')),
                ('auto_alignment', models.BooleanField(default=True, help_text='True, if the dome should be aligned activelywith the mount, else False.')),
            ],
        ),
    ]
